### ISSUE TITLE
[Question] Project state and tooling

### ISSUE THREAD

**Issue by projectzerotohero** [stevenknox/CoreBDD#14]
Hi @stevenknox 

This is a nice BDD tool and I would like to give it a try.

I'm just curious if this is ready for production apps. 
Have you tried it with Code Coverage tools?

**Comment by stevenknox** [comment]
Hi @projectzerotohero , I have been using it with production apps on a daily basis and the core functionality appears to be holding up well. It should work perfectly with code coverage tools as its using xUnit.net under the covers.

**Comment by projectzerotohero** [comment]
Great Thanks @stevenknox
