### ISSUE TITLE
[question] Comparision to specflow

### ISSUE THREAD

**Issue by tometchy** [stevenknox/CoreBDD#15]
Hi I just found your framework and ease of running it on dotnet core is awesome. But despite ease of starting to use it, is there anything more in it than specflow has? And is this production ready, or it's better not to touch it because it's not finished?

**Comment by stevenknox** [comment]
It's minimal compared to spec flow in terms of features etc however I have been using it in production for well over a year now with no issues. Most of the heavy lifting is done by xUnit, this just sits on top

**Comment by tometchy** [comment]
Great, thanks for answering. In my view your tool is much easier to use then specflow and I feel it has minimum which I need, so I think I will stick to it :)
